project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sabina Pedrazzini"
  favicon: images/flower.png

  navbar:
    logo: images/flower.png
    left:
        
      - href: whoami/index.qmd  
        text: Who am I?
        
      - href: mywork/index.qmd
        text: My work
    
    right:
      - icon: github
        href: https://github.com/sabinapedrazzini
      - icon: linkedin
        href: https://ch.linkedin.com/in/sabina-pedrazzini-543051169
      - icon: envelope
        href: "mailto:sabina.pedrazzini@gmail.com"
        
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Sabina Pedrazzini CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://github.com/sabinapedrazzini/quarto_workshop">Code to create the website</a></span>
    

format:
  html:
    theme: styles.scss
    toc: true