project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sabina Pedrazzini"
  favicon: images/flower.png
#navbar = on top of the page
  navbar:
    logo: images/flower.png
    left:
        
      - href: whoami/index.qmd  
        text: Who am I?
        
      - href: mywork/index.qmd
        text: "My work"
        #to create a menu (if too many things to display)
      #- text: More
      #  menu:
      #   - whoami/index.qmd
      #   - mywork/index.qmd
    
    right:
      - icon: github
        href: https://github.com/sabinapedrazzini
      - icon: linkedin
        href: https://ch.linkedin.com/in/sabina-pedrazzini-543051169
      - icon: envelope
        href: "mailto:sabina.pedrazzini@gmail.com"
        

#sidebar = on the side
  sidebar:
    title: "My work" #this should display it only on the page called "My work"; if the title is not specified, the sidebar will appear on every page
    #tools: 
    #  - icon: github
    #    href: https://github.com/sabinapedrazzini
    style: "floating" #"docked" if we want it more separated from the body text
    search: false
    contents:
      - text: "Home"
        href: index.qmd
     # - section: "Basics"
        #href: mywork/index.qmd
     #   contents:
       #  - text: "Home"
      #     href: index.qmd

  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Sabina Pedrazzini CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://github.com/sabinapedrazzini/quarto_workshop">Code to create the website</a></span>
    

format:
  html:
    theme: styles.scss
    toc: true