project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sabina Pedrazzini"

  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: whoami.qmd  
        text: Who am I?
        
    right: 
      - icon: github
        href: https://github.com/sabinapedrazzini
      - icon: linkedin
        href: https://ch.linkedin.com/in/sabina-pedrazzini-543051169
        
format:
  html:
    theme: styles.scss
    toc: true
